from .batchnorm import MakeHLSBatchNorm
from .binary import MakeHLSBinary
from .concat import MakeHLSConcat
from .conv import MakeHLSConv
from .elu import MakeHLSELU
from .gemm import MakeHLSGemm
from .leaky_relu import MakeHLSLeakyRelu
from .pooling import MakeHLSPooling
from .relu import MakeHLSReLU
from .permute import MakeHLSPermute
from .reshape import MakeHLSReshape
from .selu import MakeHLSSeLU
from .sigmoid import MakeHLSSigmoid
from .softmax import MakeHLSSoftmax
from .swish import MakeHLSSwish
from .tanh import MakeHLSTanh
from .thresholdedrelu import MakeHLSThresholdedRelu
